### ISSUE TITLE
update link in readme

### ISSUE THREAD

**Issue by BrockleyJohn** [bramley/phplist-plugin-contentareas#12] opened 2024-06-22 08:32 UTC
Link to plugin documentation on phplist doesn't work - suggest update to
https://resources.phplist.com/doku.php?id=plugin:contentareas

**Comment by bramley** [comment] 2024-06-22 09:37
Thanks, sorry for the problem but it has been caused by a change in the docuwiki package used on the phplist documentation site.

I have already raised an issue on phplist explaining the problem https://github.com/phpList/phplist3/issues/1043 . I think that needs to be addressed in the way I suggest so that links to plugin documentation in the phplist code itself and many existing plugins that are already installed continue working.

**Comment by bramley** [comment] 2024-06-22 20:33
The link to the plugin documentation is now working again.

**Closed as completed by bramley** 2024-06-22 20:33 UTC
