### ISSUE TITLE
Blank page and icons not displayed

### ISSUE THREAD

**Issue by rayvolvez** [bramley/phplist-plugin-contentareas#3] opened 2016-01-21 16:16 UTC
Dear Duncan,

Would appreciate if you can assist to point me to a possible issue in setup for this. 

I'm getting a blank page with the plugin enabled. While I can create the campaign, select the template, enable the plugin and go back to edit the campaign with content areas, this work flow is counter intuitive.

In addition, the icons to edit does not display. Please see appended screenshot.

![unabletodisplayimages](https://cloud.githubusercontent.com/assets/3252295/12485145/6ae6f94c-c098-11e5-8d7a-a5bedf8c265e.JPG)

I'm getting a 500 error. 

Is it a php version issue? The server is on php 5.4.

Thanks!

Regards,
Elaine

**Comment by bramley** [comment] 2016-01-21 16:26
It is not clear when the blank page happens. What action were you doing?
Have you installed Common Plugin as well?
On the Edit Areas tab, what happens if you click the Preview button?

**Comment by rayvolvez** [comment] 2016-01-21 16:30
Dear Duncan,

I clicked on "Send a New Campaign", only the tabs appear. Once I disable "Content Areas", the panel with ckeditor will then appear. I can then go to "Format", choose the template with data-edit areas defined, save it, then go back to plugins to re-enable "Content Areas". It will work this way, but this is counter intuitive.

I have installed Common Plugin.

When I click Preview, the edm looks normal and good with the template images.

Thank you for any possible assistance. :)

**Comment by bramley** [comment] 2016-01-21 17:00
So the plugin seems to work once you have selected the correct template. But when you create a new campaign, with either a default template or no template, then there is a problem. Is that correct?

On the Manage Campaign Templates page do you have a template marked as "campaign default"? Is that an ordinary template, i.e. does not have any data-edit attributes?

**Comment by bramley** [comment] 2016-01-21 17:31
> In addition, the icons to edit does not display. Please see appended screenshot.

If you right-click on the image placeholder, is there a way to see the image URL that cannot be found?

**Comment by rayvolvez** [comment] 2016-01-21 17:43
Dear Duncan,

The "campaign default" is an ordinary template and does not have any data-edit attributes. It is the default generated system template.

For the icons, I right clicked and opened the direct link to the image and was given an Internal Server Error (500).

Thanks!

![img_20160122_014004](https://cloud.githubusercontent.com/assets/3252295/12489009/3cb67366-c0a9-11e5-898e-74ed953ffe90.jpg)

**Comment by bramley** [comment] 2016-01-21 17:55
> opened the direct link to the image

What is the actual URL?

**Comment by rayvolvez** [comment] 2016-01-21 17:58
Dear Duncan,

http://(domain)/mail/admin/?page=image&pi=CommonPlugin&image=pencil.png

Unfortunately due to sensitivity of the domain, I'm unable to post the
complete url publicly. I'm getting an Internal Server (500) or Access
Denied message when I try to directly access the URL.

Thanks!

**Comment by bramley** [comment] 2016-01-21 18:55
That URL looks to be correct. I would expect to get "access denied" if you were not currently logged-in to phplist, but if you were logged-in then the image should be displayed. I cannot explain an internal server 500 error though. There might be something in the web server error log if you can get access to that.

I have tried the default system template and that doesn't cause a problem. The plugin detects that it doesn't contain any data-edit attributes and therefore doesn't display the additional "Edit Areas" tab.

As I cannot repeat the problem, unless you can find something in the web server log files, I cannot suggest anything else.

**Comment by rayvolvez** [comment] 2016-01-22 00:08
Dear Duncan,

Thank you very much.

I'm actually wondering if it is the apache / php version that's causing the
errors.

Server logs suggest nothing as well. The only error I see is mktime(),
which is unrelated to this. Tested the plugins on WAMP localhost and I have
no issues.

Thanks!

Will report back here if I have further findings.

---

Regards,
Elaine Chua 蔡依霖
M: 8498 1796                E: xoco@rayvolvez.com

---

This message (including any attachments) contains confidential information
intended for a specific individual and purpose, and is protected by law. If
you are not the intended recipient, you should delete this message and
hereby notified that any disclosure, copying, or distribution of this
message (or any part thereof), or the taking of any action based on it, is
strictly prohibited.

**Comment by rayvolvez** [comment] 2016-01-22 00:39
Dear Duncan,

May I know which physical file does [ http://(domain)/mail/admin/?page=image&pi=CommonPlugin&image=pencil.png ] links to?

As in, which is the file that sends back the image and what would be the required permission settings for this file to be user/world readable?

Thanks!

Edit: Is there any ways that I can hardcode the above dynamic url to http://(domain)/mail/admin/plugins/CommonPlugin/images/pencil.png instead?

**Comment by bramley** [comment] 2016-01-22 08:04
> The only error I see is mktime(),

does that error message refer to setting the time zone? That might be the cause of at least the image problem. You should set the timezone, as explained in the error message, or install the Timezone plugin, https://github.com/bramley/phplist-plugin-timezone , and specify the timezone on the Settings page.

**Comment by rayvolvez** [comment] 2016-01-22 12:27
Dear Duncan,

You're really amazing! That fixed all issues :)
Even the blank page issue :)

Kudos to the timezone plugin :)

**Closed as completed** 2016-01-22 12:41 UTC
